### PR TITLE
hubble: Patch Cilium DaemonSet with hubble-metrics port

### LINKED ISSUE #1422: `hubble enable` doesn't set hubble-metrics port in Cilium agent
## Bug report

Running a command enabling Hubble and Hubble metrics, e.g.:
```
cilium hubble enable --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```
results in a `hubble-metrics` service being created:
```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9965"
    prometheus.io/scrape: "true"
  labels:
    app.kubernetes.io/name: hubble
    app.kubernetes.io/part-of: cilium
    k8s-app: hubble
  name: hubble-metrics
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: hubble-metrics
    port: 9965
    protocol: TCP
    targetPort: hubble-metrics
  selector:
    k8s-app: cilium
  type: ClusterIP
```
but doesn't set `hubble-metrics` port in Cilium daemonset. That means that `hubble-metrics` Endpoints object doesn't get populated with Cilium pods IPs. Prometheus service discovery often relies on Endpoints objects, so Prometheus won't scrape Hubble metrics in that case.

If you enable Hubble metrics on `cilium install`:
```
cilium install --version="1.13.0" --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```
then `hubble-metrics` port is configured. But from the user perspective it makes sense to enable Hubble metrics when enabling Hubble:
```
cilium install
cilium hubble enable --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```
and then metrics are exposed, but `hubble-metrics` port is not configured.

A "proper" solution for this issue would be using Helm commands for all installs/updates (cilium/cilium-cli#1396). Meanwhile, a "hack" solution would be updating cilium daemonset in addition to other components on `hubble enable`.

**General Information**

- Cilium CLI version: v0.12.13
- Orchestration system version in use: k8s 1.24.7
- Platform / infrastructure information: Kind

**How to reproduce the issue**

```
cilium install --version="1.13.0"
cilium hubble enable --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```

### PR DESCRIPTION
**Pull request by lambdanis**
So far when enabling Hubble metrics in `hubble enable` command, e.g.:
```
cilium hubble enable --helm-set-string=hubble.metrics.enabled="{http,dns,drop,tcp,flow,icmp,port-distribution}"
```
the CLI created a hubble-metrics service, but didn't add a hubble-metrics port to Cilium daemonset. Then Hubble metrics were exposed by Cilium, but the hubble-metrics Endpoints object wasn't populated with the Cilium pod IPs. Prometheus scrape configs often rely on Endpoints objects, so this results in Hubble metrics not being scraped.

This patch fixes that by patching the Cilium agent daemonset with a hubble-metrics port if a metrics service is created in `hubble enable` command.

It's a rough patch and it assumes using the default Hubble metrics port (9965), and Cilium agent name ("cilium"). A proper solution to the problems would be using Helm as backend for all install/update commands (#1396).

Fixes #1422

### CODE REVIEW

File: hubble/hubble.go [hunk 1]
```diff
@@ -670,6 +671,25 @@ func (k *K8sHubble) Enable(ctx context.Context) error {
 		if _, err := k.client.CreateService(ctx, k.params.Namespace, metricsSvc, metav1.CreateOptions{}); err != nil {
 			return err
 		}
+
+		// Add hubble-metrics port to Cilium agent daemonset
+		k.Log("🔥 Patching Agent DaemonSet...")
+		patch := []byte(fmt.Sprintf(`{
```
Comment (chancez) [inline hubble/hubble.go:677]: Shouldn't we only do this if `hubble.metrics.enabled` is true?

Comment (lambdanis) [reply hubble/hubble.go:677]: It's inside the `if metricsSvc := k.generateMetricsService(); metricsSvc != nil` block - so it will happen only if `hubble-metrics` service is created, so only if `hubble.metrics.enabled` is non-empty. I think tying this patch together with the service creation makes sense.

**Review by chancez — APPROVED** [review]
