### PR TITLE
Pin image tags for arm64 support, and update hubble tags

### LINKED ISSUE #191: References to latest tag for Hubble-ui images
@lizrice reported that she deployed Hubble using `cilium hubble enable --ui` command, and image downloading failed. Looking at the source code, I see couple of references to the `:latest` tag for Hubble images - https://github.com/cilium/cilium-cli/blob/master/hubble/ui.go#L187. We switched from `:latest `tags to `:-ci` tags for other images so it would be good to keep the tags consistent.

### PR DESCRIPTION
**Pull request by aanm**
Read per commit.
Fixes #191

### CODE REVIEW

**Review by aditighag — APPROVED** [review]
Hubble image tags related changes look good to me. Thanks!

**Review by kaworu — APPROVED** [review]

**Review by kaworu — APPROVED** [review]

**Review by tgraf — APPROVED** [review]

File: connectivity/check/check.go [hunk 1]
```diff
@@ -1395,7 +1395,7 @@ func (k *K8sConnectivityCheck) deploy(ctx context.Context) error {
 			Name:   echoSameNodeDeploymentName,
 			Kind:   kindEchoName,
 			Port:   8080,
-			Image:  "quay.io/cilium/json-mock:1.2",
+			Image:  "quay.io/cilium/json-mock:v1.3.0@sha256:2729064827fa9dbfface8d3df424feb6c792a0ba07117b844349635c93c06d2b",
```
Comment (tklauser) [inline connectivity/check/check.go:1398]: Might make sense to define this in package `defaults` so it doesn't have to be repeated.

File: connectivity/check/check.go [hunk 2]
```diff
@@ -1427,7 +1427,7 @@ func (k *K8sConnectivityCheck) deploy(ctx context.Context) error {
 			Name:    ClientDeploymentName,
 			Kind:    kindClientName,
 			Port:    8080,
-			Image:   "quay.io/cilium/alpine-curl:1.1",
+			Image:   "quay.io/cilium/alpine-curl:v1.2.0@sha256:bf2f87bb761821bf57b792d45edfd3a46cf5cca4c57da3fa3fc2abcb13b89dd3",
```
Comment (tklauser) [inline connectivity/check/check.go:1430]: Same here.

**Review by tklauser — APPROVED** [review]
