### PR TITLE
hubble: Wait for Cilium to start before deploying relay/ui

### LINKED ISSUE #334: flake: hubble-relay in crash loop backoff
# flake instances

- https://github.com/cilium/cilium-cli/pull/331/checks?check_run_id=2847932537

# symptom

hubble-relay in crash loop backoff after `cilium hubble enable`:
```
DaemonSet         cilium             Desired: 2, Ready: 2/2, Available: 2/2
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Deployment        hubble-relay       Desired: 1, Unavailable: 1/1
Containers:       cilium             Running: 2
                  cilium-operator    Running: 1
                  hubble-relay       Running: 1
Image versions    cilium             quay.io/cilium/cilium:v1.9.8: 2
                  cilium-operator    quay.io/cilium/operator-generic:v1.9.8: 1
                  hubble-relay       quay.io/cilium/hubble-relay:v1.9.8: 1
Errors:           hubble-relay       hubble-relay    1 pods of DaemonSet hubble-relay are not ready
```

# other notes

i think this is just a timing issure where hubble-relay gets deployed before cilium restart is complete, and cilium is not managing hubble-relay. i'll take a stab at fixing this.

### PR DESCRIPTION
**Pull request by michi-covalent**
Hubble Relay and UI do not function properly if they are not managed by
Cilium. This commit modifies `cilium hubble enable` command to wait for
Cilium pods to become ready after the restart before deploying them.

Fixes #334

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
sample output:
```
% ./cilium hubble enable
🔑 Found existing CA in secret cilium-ca
✨ Patching ConfigMap cilium-config to enable Hubble...
♻️  Restarted Cilium pods
⌛ Waiting for Cilium to become ready before deploying other Hubble component(s)...
🔑 Generating certificates for Relay...
2021/06/17 17:34:09 [INFO] generate received request
2021/06/17 17:34:09 [INFO] received CSR
2021/06/17 17:34:09 [INFO] generating key: ecdsa-256
2021/06/17 17:34:10 [INFO] encoded CSR
2021/06/17 17:34:10 [INFO] signed certificate with serial number 273156976634734063172016924218801891264036665813
2021/06/17 17:34:10 [INFO] generate received request
2021/06/17 17:34:10 [INFO] received CSR
2021/06/17 17:34:10 [INFO] generating key: ecdsa-256
2021/06/17 17:34:10 [INFO] encoded CSR
2021/06/17 17:34:10 [INFO] signed certificate with serial number 696062360827444987883893581476716325094893503178
✨ Deploying Relay...
```

**Review by rolinh — APPROVED** [review]

**Review by nbusseneau — APPROVED** [review]
I was actually wondering the other day if this should be done in code like you did or done in workflows like we do when we wait for Cilium to be ready before enabling Cluster Mesh:

https://github.com/cilium/cilium-cli/blob/ee11876fdf23156996ee75c72fff88a94df50258/.github/in-cluster-test-scripts/multicluster.sh#L31-L41

If we move forward with this solution, I suggest we do it for Cluster Mesh as well :)

**Review by nathanjsweet — APPROVED** [review]

File: hubble/hubble.go [hunk 1]
```diff
@@ -242,6 +260,13 @@ func (k *K8sHubble) Enable(ctx context.Context) error {
 		return err
 	}
 
+	if k.params.Relay || k.params.UI {
+		k.Log("⌛ Waiting for Cilium to become ready before deploying other Hubble component(s)...")
+		if err := k.waitForDaemonset(ctx, "cilium"); err != nil {
```
Comment (tklauser) [inline hubble/hubble.go:265]: Nit:
```suggestion
		if err := k.waitForDaemonset(ctx, defaults.AgentDaemonSetName); err != nil {
```

File: internal/k8s/client.go [hunk 2]
```diff
@@ -216,6 +216,26 @@ func (c *Client) DeploymentIsReady(ctx context.Context, namespace, deployment st
 	return nil
 }
 
+// DaemonsetIsReady returns nil if the daemonset is ready, or a non-nil error otherwise.
```
Comment (tklauser) [inline internal/k8s/client.go:219]: Nit: from the function name alone I'd assume it to return a `bool` rather than an `error`. Could we maybe rename it to something like `CheckDaemonSetStatus`?

**Review by tklauser — COMMENTED** [review]
Two small nits, both not blocking. LGTM otherwise :shipit:

**Comment by michi-covalent** [comment]
thanks @tklauser ! addressed your feedback 🚀

**Review by tklauser — APPROVED** [review]
Thanks

**Review by joestringer — APPROVED** [review]

**Review by christarazi — APPROVED** [review]
